server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      force: true

spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .mustache
  datasource:
#    hikari:
#      driver-class-name: org.h2.Driver
#      jdbc-url: jdbc:h2:tcp://localhost:9092/test
#      jdbc-url: jdbc:h2:tcp://localhost:9093/test;MODE=MySQL # ./ Project root
#      username: sa
#      password: 1234
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
   init:
     schema-locations:
     - classpath:db/table.sql
     data-locations:
     - classpath:db/data.sql
  devtools:
    restart:
      enabled: true
      additional-exclude: staic/**,public/**

mybatis:
  mapper-locations:
    - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true